# Generated by Django 4.1.2 on 2022-10-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igles', '0002_usuarios_dificultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dificultad',
            field=models.CharField(choices=[('1', 'To Practice'), ('2', 'Tests')], default='1', max_length=25),
        ),
    ]
