# Generated by Django 4.1.2 on 2022-11-02 22:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('igles', '0003_alter_usuarios_dificultad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('motivo', models.CharField(max_length=250)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='dificultad',
            field=models.CharField(max_length=25),
        ),
    ]
